### ISSUE TITLE
Files not installed with package install

### ISSUE THREAD

**Issue by kevinwasie** [WebPx/WebPx.AdminLTE.AspNetCore#1]
Hello, I run the installer, "Install-Package WebPx.AdminLTE.AspNetCore".

The package gets installed and the installer completes. However, no files actually get written to the project except the Nuget package.

No pages, scripts or anything. No new folders. Any assistance is appreciated.

![Screen Shot 2020-05-06 at 1 40 23 PM](https://user-images.githubusercontent.com/64920968/81209988-3893be00-8f9f-11ea-92da-823cd816ab91.png)

**Comment by Anteres** [comment]
I copy Pages from Template project. But SideBar is missing.

**Comment by jlchavez** [comment]
Files are not added since those files are compiled to C# and for the time being it would break the purpose of the nuget to have a Razor Class Library. Will research a way to include those files as a file template for Visual Studio in an Extension.

In the mean time, please copy any files you need from the sample/templates projects.
